kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
stringData:
  .dockerconfigjson: {"auths":{"ghcr.io":{"auth":"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"}}}
