name: Docker Image CI
# Branch from which the code is fetching
on:
  push:
    branches: [ main ]
# Define the env variable which need to be used
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GIT_USER }}
        password: ${{ secrets.GIT_PASS }}
    
    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
   
    -   name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.GIT_USER }}/${{ github.repository }}:latest





